---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Creates a bucket to store uploaded files"

Parameters:
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
  AppDomain:
    Type: String

Resources:  
  AppCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Sub "${AppDomain}"
      DomainValidationOptions:
        - DomainName: !Sub "${AppDomain}"
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: "DNS"

Outputs:
  Certificate:
    Value: !Ref "AppCertificate"
